from __future__ import annotations

from typing import Protocol
from uuid import UUID

from trellis.learn_models import LearningEntry, LearningThread


class LearningThreadRepository(Protocol):
    def save(self, thread: LearningThread) -> LearningThread: ...
    def get(self, thread_id: UUID) -> LearningThread | None: ...
    def list_active(self, user_id: UUID) -> list[LearningThread]: ...
    def deactivate(self, thread_id: UUID) -> None: ...


class LearningEntryRepository(Protocol):
    def save(self, entry: LearningEntry) -> LearningEntry: ...
    def recent(self, thread_id: UUID, *, limit: int) -> list[LearningEntry]: ...
