-- Meaning index: one Trellis-wide catalogue of semantic embeddings. Every domain
-- files uniform rows here (kind + entity id + text + vector); recall runs a single
-- cosine search across the lot. Replaces the per-table embedding columns from 005
-- — one index scales to every kind of thing without a new column per type.

CREATE TABLE IF NOT EXISTS memory_index (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES trellis_users(id) ON DELETE CASCADE,
    entity_kind TEXT NOT NULL,
    entity_id UUID NOT NULL,
    content TEXT NOT NULL,
    embedding vector(1536),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (entity_kind, entity_id)
);

CREATE INDEX IF NOT EXISTS memory_index_user_idx
    ON memory_index(user_id);

CREATE INDEX IF NOT EXISTS memory_index_embedding_idx
    ON memory_index USING hnsw (embedding vector_cosine_ops);

-- Retire the per-table embedding columns 005 added — the meaning index owns
-- embeddings now. Derived data (regenerated by the backfill), so dropping is safe.
DROP INDEX IF EXISTS efforts_embedding_idx;
DROP INDEX IF EXISTS captures_embedding_idx;
ALTER TABLE efforts  DROP COLUMN IF EXISTS embedding;
ALTER TABLE captures DROP COLUMN IF EXISTS embedding;
