-- Move the meaning index to the LOCAL embedder (fastembed / bge-small, 384 dims).
-- The previous embeddings came from GitHub Models (text-embedding-3-small, 1536
-- dims), which was retired on 30 Jul 2026. Those vectors are dead AND the wrong
-- dimension, so the column is resized to vector(384); every row's embedding is
-- cleared to NULL and re-generated by the backfill with the local model.
-- Embeddings are derived data, so dropping/clearing them is safe.

DROP INDEX IF EXISTS memory_index_embedding_idx;

ALTER TABLE memory_index DROP COLUMN IF EXISTS embedding;
ALTER TABLE memory_index ADD COLUMN embedding vector(384);

CREATE INDEX IF NOT EXISTS memory_index_embedding_idx
    ON memory_index USING hnsw (embedding vector_cosine_ops);
